require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DoitListsController do

  # This should return the minimal set of attributes required to create a valid
  # DoitList. As you add validations to DoitList, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DoitListsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all doit_lists as @doit_lists" do
      doit_list = DoitList.create! valid_attributes
      get :index, {}, valid_session
      assigns(:doit_lists).should eq([doit_list])
    end
  end

  describe "GET show" do
    it "assigns the requested doit_list as @doit_list" do
      doit_list = DoitList.create! valid_attributes
      get :show, {:id => doit_list.to_param}, valid_session
      assigns(:doit_list).should eq(doit_list)
    end
  end

  describe "GET new" do
    it "assigns a new doit_list as @doit_list" do
      get :new, {}, valid_session
      assigns(:doit_list).should be_a_new(DoitList)
    end
  end

  describe "GET edit" do
    it "assigns the requested doit_list as @doit_list" do
      doit_list = DoitList.create! valid_attributes
      get :edit, {:id => doit_list.to_param}, valid_session
      assigns(:doit_list).should eq(doit_list)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DoitList" do
        expect {
          post :create, {:doit_list => valid_attributes}, valid_session
        }.to change(DoitList, :count).by(1)
      end

      it "assigns a newly created doit_list as @doit_list" do
        post :create, {:doit_list => valid_attributes}, valid_session
        assigns(:doit_list).should be_a(DoitList)
        assigns(:doit_list).should be_persisted
      end

      it "redirects to the created doit_list" do
        post :create, {:doit_list => valid_attributes}, valid_session
        response.should redirect_to(DoitList.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved doit_list as @doit_list" do
        # Trigger the behavior that occurs when invalid params are submitted
        DoitList.any_instance.stub(:save).and_return(false)
        post :create, {:doit_list => { "title" => "invalid value" }}, valid_session
        assigns(:doit_list).should be_a_new(DoitList)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DoitList.any_instance.stub(:save).and_return(false)
        post :create, {:doit_list => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested doit_list" do
        doit_list = DoitList.create! valid_attributes
        # Assuming there are no other doit_lists in the database, this
        # specifies that the DoitList created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DoitList.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => doit_list.to_param, :doit_list => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested doit_list as @doit_list" do
        doit_list = DoitList.create! valid_attributes
        put :update, {:id => doit_list.to_param, :doit_list => valid_attributes}, valid_session
        assigns(:doit_list).should eq(doit_list)
      end

      it "redirects to the doit_list" do
        doit_list = DoitList.create! valid_attributes
        put :update, {:id => doit_list.to_param, :doit_list => valid_attributes}, valid_session
        response.should redirect_to(doit_list)
      end
    end

    describe "with invalid params" do
      it "assigns the doit_list as @doit_list" do
        doit_list = DoitList.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DoitList.any_instance.stub(:save).and_return(false)
        put :update, {:id => doit_list.to_param, :doit_list => { "title" => "invalid value" }}, valid_session
        assigns(:doit_list).should eq(doit_list)
      end

      it "re-renders the 'edit' template" do
        doit_list = DoitList.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DoitList.any_instance.stub(:save).and_return(false)
        put :update, {:id => doit_list.to_param, :doit_list => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested doit_list" do
      doit_list = DoitList.create! valid_attributes
      expect {
        delete :destroy, {:id => doit_list.to_param}, valid_session
      }.to change(DoitList, :count).by(-1)
    end

    it "redirects to the doit_lists list" do
      doit_list = DoitList.create! valid_attributes
      delete :destroy, {:id => doit_list.to_param}, valid_session
      response.should redirect_to(doit_lists_url)
    end
  end

end
